config/routes.rb
PoasterApi::Application.routes.draw do
  
  root :to => 'home#index'
  match "/" => "home#index",as: :home
  devise_for :users,:controllers => {:confirmations => 'confirmations'},skip: [:registration] do 
    get '/login' => "devise/sessions#new", :as => :new_user_session
    post '/login' => 'devise/sessions#create', :as => :user_session
    delete '/logout' => 'devise/sessions#destroy', :as => :destroy_user_session
  end  

  devise_scope :user do
    get '/confirmation' => 'confirmations#show'
    put "/confirm" => 'confirmations#confirm'
  end

  match "/privacy-policy" => "home#privacy_policy",:as => :privacy_policy
  match "/service-url" => "home#service_policy" ,as: :service_policy
  match "/support" => "home#support",as: :support
  match "/marketing" => "home#marketing",as: :marketing
  match "/user_support" => "home#user_support",:as => :user_support
  match '/itunes' =>  'home#itunes',as: :itunes

  scope "users" do
    get 'statistics' => "users#statistics" ,as: :statistics
    get 'password/new' => 'users#new_password' , as: :new_password
    post 'password/create' => 'users#create_password' ,as: :create_password
    post 'picture' => 'users#profile_picture',as: :profile_picture
  end

  match "/auth/:provider/callback" => "authorizations#create"
  match '/auth/failure' => 'authorizations#failure'
  match '/errors_notifications' => 'error_notifications#notify'
  

  match "/share"=>"authorizations#share"
  match "/verify_social_accounts" => "authorizations#verify_social_accounts"
  match "/poaster/:id/:name"=>"shareatives#show",:as=>"show_poaster"
  match "/poaster/shareative/:id/email_content" => "shareatives#email_content",:as => "email_content"
  resources :poaster_instances,:only => [:index,:show]
  resources :shareatives,:only => [:show] 

end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable,:recoverable, :rememberable, :trackable, :validatable,:confirmable

  include RoleModel
  roles_attribute :roles_mask
  roles :poast_master, :curator, :poast_marketer, :super_admin

  belongs_to :company
  has_many :access_controls ,dependent: :destroy
  attr_accessible :email, :password, :password_confirmation, :remember_me,
                  :first_name, :last_name, :department,:roles, :company_attributes,:profile
  # has_many :poaster_instances,through: :access_controls ,dependent: :destroy
  scope :active , where(active: true)
  mount_uploader :profile,ProfileUploader

  def as_json
    {
      id: id.to_s,
      name: full_name,
      email: email,
      company: company.as_json,
      default_poaster_instance: default_poaster_instance.as_json,
      poaster_instances: poaster_instances.as_json
    }
  end

  def validate_password?(password)
    unless valid_password?(password)
      self.errors.add(:password,'current password is not valid')
    end
    return errors.empty?
  end

  def password_valid?
    self.errors[:password] = 'must be present' if self.password.blank?
  
    if self.password and self.password != self.password_confirmation
      self.errors[:password_confirmation] = 'does not match'
    end
    self.errors.empty?
  end

  def statistics
    {
      facebook: facebook_statistic.count,
      twitter: twitter_statistic.count,
      linkedin: linkedin_statistic.count,
      email: email_statistic.count,
      poast: total_statistic,
      measurable: total_measurable
    }
  end

  def full_name
    [first_name,last_name].join(' ')
  end

  def poaster_instances
    company.poaster_instances
  end
 
  def build_poaster_json(poaster_instance_id="0")
    find_poaster_instance(poaster_instance_id).as_json.merge facades: facade_json
  end

  def poaster_instance_schema
    find_poaster_instance.as_json.merge facades: facade_json
  end

  def facade_json
    Facade.relevant_facades(company.id,find_poaster_instance.id).as_json
  end

  def find_poaster_instance(poaster_instance_id="0")
    ## 0 implies no match for the enumerator and take the default poaster instances
    (poaster_instances.where(:id => id).first || default_poaster_instance)
  end

  def default_poaster_instance
    poaster_instances.first
  end

  def welcome_email
    UserMailer.welcome_email(self).deliver
  end

  private
  
  def facebook_statistic
    @facebook_statistic ||= FacebookStatistic.where(user_id: id,company_id: company.id)
  end

  def twitter_statistic
    @twitter_statistic ||= TwitterStatistic.where(user_id: id,company_id: company.id)
  end

  def linkedin_statistic
    @linkedin_statistic ||= LinkedinStatistic.where(user_id: id,company_id: company.id)
  end

  def email_statistic
    @email_statistic ||= EmailStatistic.where(user_id: id,company_id: company.id)
  end

  def total_statistic
    facebook_statistic.count + twitter_statistic.count  + linkedin_statistic.count + email_statistic.count
  end
  
  def poast_statistic
    [facebook_statistic.count-1,0].max + [twitter_statistic.count-1,0].max + [linkedin_statistic.count-1,0].max + [email_statistic.count-1,0].max
  end

  def total_measurable
    @measurable_statistic ||= (first_poasting_measurable + poasting_measurable + facebook_measurable + twitter_measurable + linkedin_measurable + email_measurable)
  end

  def first_poasting_statistic
    [1,facebook_statistic.count].min + [1,twitter_statistic.count].min + [1,linkedin_statistic.count].min + [1,email_statistic.count].min
  end
  
  def first_poasting_measurable
    @first_poasting_measurable ||= first_poasting_statistic * 10
  end
  
  def poasting_measurable
    @poasting_measurable ||= poast_statistic * 25
  end
  
  def facebook_measurable
    @facebook_measurable ||= [facebook_statistic.sum('likes') , facebook_statistic.sum('comments')].sum * 50
  end
  
  def twitter_measurable
    @twitter_measurable ||= twitter_statistic.sum('retweets') * 50
  end
  
  def linkedin_measurable
    @linkedin_measurable ||= [linkedin_statistic.sum('likes'),linkedin_statistic.sum('comments')].sum * 50
  end
  
  def email_measurable
    0
  end
  
  def total_company_statistics
    FacebookStatistic.statistics(company_id).count + TwitterStatistic.statistics(company_id).count + LinkedinStatistic.statistics(company_id).count + EmailStatistic.statistics(company_id).count
  end

  def total_employees
    User.where(company_id: company_id).count
  end  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    respond_to do |format|
      format.json { render json: current_user.as_json }
    end
  end

  def new_password ; end

  def create_password
    if params[:password_options].present? and create_password?
      flash[:success] = "Successfully updated password"
      render json: {status: "success", message: 'Password has been updated'}
    else
      render json: {status: 'failed', message: humaize_errors }
    end
  end


  def statistics
    render json: current_user.statistics
  end

  def profile_picture
    delete_unwanted_params
    if current_user.update_attributes(params[:user])
      render json: { status: :success,small_pic: current_user.profile.url(:thirty), big_pic: current_user.profile.url(:forty_two) }
    else
      render json: { status: :failed,small_pic: current_user.profile.url(:thirty), big_pic: current_user.profile.url(:forty_two),message: humaize_errors}
    end
    rescue => exception
      render json: { status: :failed, small_pic: current_user.profile.url(:thirty), big_pic: current_user.profile.url(:forty_two),message: exception.message}
  end  

  private
  def create_password?
    current_user.validate_password?(params[:password_options].delete(:old_password)) and current_user.update_attributes(params[:password_options])
    current_user.errors.empty?
  end 

  def humaize_errors
    current_user.errors.values.flatten.join(" ")
  end


  def delete_unwanted_params
    params[:user].reject! { |key,value| key.to_sym != :profile }
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit_password.html.erb
<div id="authentication">
  <img id="poaster_brand_auth" src="/assets/poaster_brand.svg">
  <%= flash[:error] %>
  <%= form_tag update_password_path ,method: :post do %>
    <%= password_field_tag 'password_options[password]',nil,placeholder: 'Password' %>
    <%= password_field_tag 'password_options[password_confirmation]',nil,placeholder: 'Password Confirmation' %>
    <%= hidden_field_tag :reset_password_token,params[:reset_password_token] %>
    <%= submit_tag 'Reset Password', :class => 'btn btn-pos btn-big', :id => 'signInBtn' %>
  <%end%>
</div>

app/views/users/forgot_password.erb
<div id="error">
  <%= flash[:error] %>
</div>
<div id="authentication">
  <img id="poaster_brand_auth" src="/assets/poaster_brand.svg">
  <%= form_tag send_password_instruction_path ,method: :post do %>
    <%= text_field_tag :email ,nil,:placeholder => "Email" %>
    <%= submit_tag 'Send Instructions', :class => 'btn btn-pos btn-big', :id => 'signInBtn' %>
  <%end%>
</div>

app/views/users/login.html.erb
<!-- <span class="formNote">Don't have an account? -->
<!-- <a href="#">Sign up</a>/<a href=" --><%#= ApiConfig.forgot_password_url %><!-- ">Forgot Password</a></span> -->

<div id="authentication">
  <img id="poaster_brand_auth" src="/assets/poaster_brand.svg">

  <%= form_for(@user, url: logged_in_path,method: :post) do |f| %>
    <%= f.text_field :email, :placeholder => "Email" %>
    <%= f.password_field :password, :placeholder => "Password" %>
    <%= f.submit 'SIGN IN', :class => 'btn btn-pos btn-big', :id => 'signInBtn' %>
  <% end %>

  <div id="forgotPassword" class="bottomLink">
    <%= link_to 'Forgot Password' , '/users/password/forgot' %>
  </div>
</div>

app/views/users/new_password.html.erb
<div id="authentication">
  <img id="poaster_brand_auth" src="/assets/poaster_brand.svg">
  <%= flash[:error] %>
  <%= form_tag create_password_path ,method: :post do %>
    <%= password_field_tag 'password_options[old_password]' ,nil,:placeholder => "Old Password" %>
    <%= password_field_tag 'password_options[password]' ,nil,:placeholder => "New Password" %>
    <%= password_field_tag 'password_options[password_confirmation]' ,nil,:placeholder => "Confirm Password" %>
    <%= submit_tag 'Change Password', :class => 'btn btn-pos btn-big', :id => 'signInBtn' %>
  <%end%>
</div>